// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh1-e0Kvyt-CZ96ia1jr1xbXszPuUDNM8',
    appId: '1:971193985300:web:6594a8d694217ed847ba01',
    messagingSenderId: '971193985300',
    projectId: 'redland-green-bird-surve-3ef37',
    authDomain: 'redland-green-bird-surve-3ef37.firebaseapp.com',
    databaseURL: 'https://redland-green-bird-surve-3ef37-default-rtdb.firebaseio.com',
    storageBucket: 'redland-green-bird-surve-3ef37.appspot.com',
    measurementId: 'G-WV8EZ51B98',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhwa9VDBFj7_KL5kt7aBg_o-mcsJizwlo',
    appId: '1:971193985300:android:b5e7f1aa6a0e141647ba01',
    messagingSenderId: '971193985300',
    projectId: 'redland-green-bird-surve-3ef37',
    databaseURL: 'https://redland-green-bird-surve-3ef37-default-rtdb.firebaseio.com',
    storageBucket: 'redland-green-bird-surve-3ef37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUfQxJlk-Px2b9nEGS7tFuFLAcwM9OYYU',
    appId: '1:971193985300:ios:0f03084edab6ddf047ba01',
    messagingSenderId: '971193985300',
    projectId: 'redland-green-bird-surve-3ef37',
    databaseURL: 'https://redland-green-bird-surve-3ef37-default-rtdb.firebaseio.com',
    storageBucket: 'redland-green-bird-surve-3ef37.appspot.com',
    iosClientId: '971193985300-t3cslr3suq0ao7323s6e3d7b9ng7pnlh.apps.googleusercontent.com',
    iosBundleId: 'org.uk.rgcg.redlandGreenBirdSurvey',
  );
}
